In [1]:
import numpy as np

In [2]:
m=np.array([[1,3],[3,1]])
m

array([[1, 3],
       [3, 1]])

In [3]:
v=np.array([-0.707,-0.707])
lamb=4.0

In [6]:
#Compararaemos o produto de M por v (np.dot(M,v)) com lambda*v
np.dot(m,v),4*v

(array([-2.828, -2.828]), array([-2.828, -2.828]))

In [12]:
#A=B!!!!

In [9]:
a,v=np.linalg.eig(m) # Gera os auto-valores e auto-vetores
a,v

(array([ 4., -2.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [10]:
np.dot(m,v[:,0]), a[0]*v[:,0]

(array([2.82842712, 2.82842712]), array([2.82842712, 2.82842712]))