In [1]:
import numpy as np

In [2]:
M=np.array([[1,-2],[3,9]]) #transformei lista em array para usar as muitas funções e métodos do numpy
M

array([[ 1, -2],
       [ 3,  9]])

In [3]:
#Obtendo autovalores e autovetores com a biblioteca de Àlgebra Linear (linalg)

In [4]:
auto_val,auto_vet=np.linalg.eig(M)
auto_val,auto_vet

(array([1.83772234, 8.16227766]),
 array([[-0.92235669,  0.26895177],
        [ 0.3863394 , -0.96315364]]))

Os autovetores obtidos pélo numpy são (-0.92,038) para autovalor 1.83  e (0.26,-0.96) para autovalor 8.16
Obtivemos (na mão)...(1, -0.42) para 1.83 e (1, -3.58) para 8.16...por que a diferença?
A diferença é que o numpy já exibe os autovetores com norma 1...

In [5]:
#por exemplo, se dividirmos o autovetor (1,-3.58) pela sua norma

v=auto_vet[:,1]#autovetor do 8.16
v=v/np.linalg.norm(v)
v

array([ 0.26895177, -0.96315364])

In [6]:
v1=np.array([1,-0.42])
v2=np.array([1,-3.58])