# Mack Aprendizado Não Supervisionado - Revisão numpy




NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects, and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
fonte: https://numpy.org/

In [2]:
import numpy as np
import math

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. 

Transformando uma lista e um array

In [6]:
la=np.array([1,3,4,5])
la, type(la)

(array([1, 3, 4, 5]), numpy.ndarray)

Diferente das listas, um slice em um array não gera uma cópia...assim o slice é uma "view" do array original. Vamos a um exemplo:

In [7]:
a1=np.array([1,2,3,4,5])
a2=a1[:3]
a2
a2[0]=100
a2,a1

(array([100,   2,   3]), array([100,   2,   3,   4,   5]))

Um array n-dimensional (bi-dimensional, por exemplo) pode ser criado também a partir de uma lista..vamos a um exemplo..

In [8]:
m=np.array([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

A indexação no array é feita por vírgulas. Exemplo, para acessar o elemento de índices 1,1 , podemos usar a[1,1], sendo a o array...exemplos.

In [12]:
m[0,0], m[0][0], m[1,1], m[1][1]


(1, 1, 4, 4)

Produto interno entre dois vetores (de mesma dimensão) x (x1,x2,x3...,xn) e y (y1,y2,y3,..,yn) é dado por: x1y1+x2y2+x3y3+...+xnyn
O produto interno entre x e y é simbolizado por &lsaquo;x,y&rsaquo;

As duas listas lx e ly abaixo representam dois vetores x e y. Obtenha o produto interno deles (inner)

In [13]:
lx=[1.0,2.0,3.0]
ly=[0.0,4.0,7.0]
x=np.array(lx)
y=np.array(ly)
inner=0
#continue o código
inner = 0
for i in range(len(lx)):
    inner += lx[i]*ly[i]
inner


29.0

Agora vamos usar o numpy para obter o produto interno...

In [14]:
np.inner(lx, ly)

29.0

Vamos obter a norma Euclidiana de um vetor x...ela é dada por raiz(&lsaquo;x,x&rsaquo;). É o "módulo do vetor".
Exemplo, o vetor 4,3 tem norma 5...(Pitágoras..ah vá)...vamos obter a norma dele com numpy.

In [15]:
v = np.array([4,3])
math.sqrt(np.inner(v,v))

5.0

In [16]:
np.linalg.norm(v)

5.0

O cosseno entre dois vetores x e y é dado por &lsaquo;x,y&rsaquo; /||x||.||y||  ||v|| é o módulo do vetor v
Vamos fazer pela definição 

In [25]:
x=np.array((4,3))
y=np.array((6,5))

np.inner(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))


0.9986876634765887

O cosseno pode ser uma medida de similaridade entre dois vetores. Primeiro vamos criar a função cosseno, que recebe dois vetores e devolve um número entre -1 e 1

In [23]:
def cos_vet(v1, v2):
    return np.inner(v1, v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
cos_vet(x, y)

1.0

A lista luser1, luser2 e luser3 mostra se esses usuários gostaram ou não dos filmes 0,1,2,3,4,5...
Descubra quem é mais similar user1 e user2, user2 e user3 ou user1 e user3

In [22]:
luser1=np.array([1,1,0,0,1])
luser2=np.array([0,1,0,0,1])
luser3=np.array([1,1,1,0,1])
LU=np.array([luser1,luser2,luser3])


In [26]:
cos_vet(LU[0], LU[1]), cos_vet(LU[1], LU[2]), cos_vet(LU[0], LU[2])

(0.8164965809277259, 0.7071067811865475, 0.8660254037844387)

Com numpy, podemos fazer coisas simples como multiplicar um escalar por um vetor...

In [27]:
2*m

array([[2, 4],
       [6, 8]])

Somar vetores

In [29]:
m+m+m

array([[ 3,  6],
       [ 9, 12]])

Vamos criar uma matriz, partindo de uma lista de linhas

In [30]:
m=np.array([[1,2,3],[3,5,0],[1,0,3]])
m

array([[1, 2, 3],
       [3, 5, 0],
       [1, 0, 3]])

Vamos obter a transposta de m "na mão"

In [33]:
mt = np.zeros((3,3))

for i in range(len(m)):
    mt[:,i]=m[i,:]
mt

array([[1., 3., 1.],
       [2., 5., 0.],
       [3., 0., 3.]])

Agora, obter a transposta com numpy

In [34]:
mt2 = m.T
mt2

array([[1, 3, 1],
       [2, 5, 0],
       [3, 0, 3]])

Podemos fazer, com numpy, várias operações que envolvem matrizes...soma, multiplicação...etc

In [38]:
m1=np.array([[1,2],[2,8]])
m2=np.array([[0,1],[5,2]])

m1+m2, np.dot(m1,m2)

(array([[ 1,  3],
        [ 7, 10]]),
 array([[10,  5],
        [40, 18]]))

In [39]:
print(np.dot(m1,m2)) #Agora sim...o produto de duas matrizes

[[10  5]
 [40 18]]


Podemos também (quando possível) inverter uma matriz

In [47]:
m3 = m1 + m2
m3

array([[ 1,  3],
       [ 7, 10]])

In [48]:
m3i = np.linalg.inv(m3)
m3i

array([[-0.90909091,  0.27272727],
       [ 0.63636364, -0.09090909]])

Mostre que m1_inv é de fato a inversa de m1...

In [49]:
np.dot(m3,m3i)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

Resolva o sistema de equações lineares abaixo com numpy<br/>
3x+y=10<br/>
x-y=-2

In [53]:
me = np.array([[3,1], [1,-1]])
mei = np.linalg.inv(me)
np.dot(mei, np.array([10,-2]))

array([2., 4.])