# Mack Aprendizado Não Supervisionado - Standardization

Partiremos da lista salario (em milhares de reais), geraremos um array e depois faremos a standardização

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [3]:
sal=[2,1,3,2,4,5,6,3,30,25,33,70,12,5,1.5,3,2,]
sal_feat=np.array(sal)
sal_feat=sal_feat.reshape(-1,1)
sal_feat

array([[ 2. ],
       [ 1. ],
       [ 3. ],
       [ 2. ],
       [ 4. ],
       [ 5. ],
       [ 6. ],
       [ 3. ],
       [30. ],
       [25. ],
       [33. ],
       [70. ],
       [12. ],
       [ 5. ],
       [ 1.5],
       [ 3. ],
       [ 2. ]])

In [5]:
#Cálculo da média e desvio padrão da feature
m=sal_feat.mean()
d=sal_feat.std()
m,d

(12.205882352941176, 17.60603073776427)

Obter o array sal_s, standardizado

In [6]:
sal_feat_s=(sal_feat-m)/d

In [7]:
sal_feat_s


array([[-0.57968105],
       [-0.63647977],
       [-0.52288233],
       [-0.57968105],
       [-0.46608361],
       [-0.40928489],
       [-0.35248617],
       [-0.52288233],
       [ 1.0106831 ],
       [ 0.7266895 ],
       [ 1.18107925],
       [ 3.28263187],
       [-0.01169385],
       [-0.40928489],
       [-0.60808041],
       [-0.52288233],
       [-0.57968105]])

Apresente a média e desvio padrão da feature standardizada

In [8]:
sal_feat_s.mean(),sal_feat_s.std()

(5.224578939412501e-17, 1.0)

Agora usando o sklearn

In [9]:
scaler = StandardScaler()
scaler.fit(sal_feat)
sal_feat_2=scaler.transform(sal_feat)
sal_feat_2

array([[-0.57968105],
       [-0.63647977],
       [-0.52288233],
       [-0.57968105],
       [-0.46608361],
       [-0.40928489],
       [-0.35248617],
       [-0.52288233],
       [ 1.0106831 ],
       [ 0.7266895 ],
       [ 1.18107925],
       [ 3.28263187],
       [-0.01169385],
       [-0.40928489],
       [-0.60808041],
       [-0.52288233],
       [-0.57968105]])

Faremos o scaler min max (de -1 a 1), ainda com sklearm


In [10]:
mmscaler=MinMaxScaler((-1,1))
mmscaler.fit(sal_feat)
sal_feat_mm=mmscaler.transform(sal_feat)
sal_feat_mm

array([[-0.97101449],
       [-1.        ],
       [-0.94202899],
       [-0.97101449],
       [-0.91304348],
       [-0.88405797],
       [-0.85507246],
       [-0.94202899],
       [-0.15942029],
       [-0.30434783],
       [-0.07246377],
       [ 1.        ],
       [-0.68115942],
       [-0.88405797],
       [-0.98550725],
       [-0.94202899],
       [-0.97101449]])