# Exercicio Regressão Linear

Considere o dataset a seguir. O dataset apresenta um conjunto de caracteristicas para o levantamento de preços de residências para a região de boston

In [1]:
import numpy as np
from sklearn.datasets import load_boston

boston = load_boston()
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

## Parte 1 -  Analise dos dados

Observe os dados de forma grafica e veja a correlação entre as diferentes features do modelo. Observe quais são as melhores features do modelo. Considere o`pairplot`como um bom candidato para a tarefa 

In [2]:
### Seu codigo aqui. Voce pode utilizar quantas celulas voce achar necessario.

## Parte 2 - Utilizando a biblioteca do Sklearn

### Parte 2.1 - Separando os conjuntos de treinamento e teste

Separe o seu dataset com as features que você achou mais conveniente (podem ser todas as features inclusive) em um conjunto de treinamento e teste. Utilize a proporção 80%-20% 

In [22]:
# Exemplo
# Observe que os vetores X e y sao repartidos
# em dois vetores com 70% e 30% dos dados originais
from sklearn.model_selection import train_test_split


X, y = np.arange(10).reshape((5, 2)), range(5)
print(f"Vetor de features original \n{X}")
print(f"Vetor de previsoes original \n{y}")


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3)

print(f"Vetor de features de treinamento\n{X_train}")
print(f"Vetor de previsoes de treinamento \n{y_train}")

print(f"Vetor de features de teste\n{X_test}")
print(f"Vetor de previsoes de teste\n{y_test}")

Vetor de features original 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Vetor de previsoes original 
range(0, 5)
Vetor de features de treinamento
[[2 3]
 [8 9]
 [6 7]]
Vetor de previsoes de treinamento 
[1, 4, 3]
Vetor de features de teste
[[0 1]
 [4 5]]
Vetor de previsoes de teste
[0, 2]


### Parte 2.2 - Criando um regressor com a biblioteca `sklearn`

Crie um regressor utilizando a biblioteca padrão do `sklearn`. Utilize o conjunto de treinamento para fitar o modelo.

In [21]:
# Seu codigo aqui

### Parte 2.3 - Verificando qualidade do modelo

Observe a qualidade do seu regressor com o uso do RMSE. O RMSE é uma função que calcula o erro médio quadrado do regressor e dado pela seguinte equação.

$$\mathrm{RMSE}=\left[\sum_{i=1}^{N}\left(y_i-\bar{y}\right)^{2} / N\right]^{1 / 2}$$

Onde:
* $y_i$ corresponde a cada saida do regressor
* $\bar{y}$ média das saidas do regressor
* $N$ número de elementos


In [23]:
# Seu codigo aqui

## Parte 3 - Criando um modelo de regressão linear do zero

Utilze o modelo apresentado na aula para criar um regressor linear utilizando apenas a biblioteca numpy como base. Para tal, implemente o método dos mínimos quadrados apresentado em aula e verifique a qualidade do modelo assim como mostrado na **Parte 2.3**

In [25]:
# Seu codigo aqui